In [2]:
import numpy as np
import pandas as pd
import import_particle_data as i_p_d
from trajectory import Trajectory
from particlemonitor import ParticleMonitor
import os
import altair as alt
alt.enable_mime_rendering()
from monitor_quantities import *

In [3]:
data_path = os.path.dirname(os.getcwd()) + "\\PhaseSpaceEval\\data3\\"
print(data_path)

X:\hapahl\PhD\GitHubRepos\CST-Eval-Scripts\python\PhaseSpaceEval\data3\


In [4]:
constantsFile = data_path + "particle_constants.txt"
particle_constants = i_p_d.import_particle_constants(constantsFile)

In [5]:
trajectoriesFile = data_path + "particle_trajectories.txt"
particle_trajectories = i_p_d.import_particle_trajectories(trajectoriesFile)

In [6]:
sourceIDFile = data_path + "source_names.txt"
names = i_p_d.import_source_names(sourceIDFile)
print(names)

{16777220: 'particle interface 1'}


In [7]:
particle_constants.head()

mass   macroCharge  sourceID
particleID                                      
0           2.007146e-26  4.882776e-13  16777220
1           2.007146e-26  4.882776e-13  16777220
2           2.007146e-26  4.882776e-13  16777220
3           2.007146e-26  4.882776e-13  16777220
4           2.007146e-26  4.882776e-13  16777220

In [8]:
particle_trajectories[0].head()

time             x             y         z            px            py  \
0 -0.000488  0.000000e+00  0.000000e+00  0.000000  0.000000e+00  0.000000e+00   
1  0.008056 -1.209744e-12 -2.738808e-18  0.013656 -8.950678e-13 -2.024486e-18   
2  0.062557 -7.335628e-11 -1.629990e-16  0.106043 -7.151656e-12 -1.576261e-17   
3  0.400008 -3.023926e-09 -5.941202e-15  0.678077 -4.636395e-11 -8.580548e-17   
4  1.257675 -2.946653e-08 -3.961229e-14  2.131958 -1.499131e-10 -1.404259e-16   

         pz  
0  0.005655  
1  0.005655  
2  0.005655  
3  0.005655  
4  0.005655

In [9]:
dtr = Trajectory(particle_trajectories[0],particle_constants.loc[[0]])
pm = ParticleMonitor(302, trajectory=dtr)

In [10]:
trajectories = []
for particleID in particle_trajectories.keys():
    trajectories.append(Trajectory(particle_trajectories[particleID], particle_constants.loc[[particleID]]))

In [11]:
for traj in trajectories:
    pm.record_intersect(traj)

In [12]:
data = pm.get_events()
data.head()

particleID  sourceID     t_event      ps_u         ps_up      ps_v  \
0           0  16777220  302.000000  0.000000 -1.606766e-14  0.000000   
1           1  16777220  305.851546  5.959886 -1.459628e+01  0.000001   
2           2  16777220  304.704716  4.438826 -9.510465e+00  6.955784   
3           3  16777220  302.017618  0.173667  6.008896e-01  9.539995   
4           4  16777220  299.424153 -4.589379  9.112135e+00  6.633542   

          ps_vp      ps_l      ps_delta  
0 -3.946328e-20 -0.000000  0.000000e+00  
1  1.037771e-05 -6.529172  5.304683e-06  
2 -9.481840e-01 -4.585057  3.175611e-06  
3 -2.445803e+00 -0.029867 -2.695271e-07  
4 -2.070382e+00  4.366597 -1.717785e-06

In [13]:
ps_u = alt.Chart(data).mark_circle().encode(
    x=alt.X('ps_u', axis=alt.Axis(title='X')),
    y=alt.Y('ps_up', axis=alt.Axis(title='X')))
ps_u


<altair.VegaLite object>

In [14]:
ps_v = alt.Chart(data).mark_circle().encode(
    x=alt.X('ps_v', axis=alt.Axis(title='Y')),
    y=alt.Y('ps_vp', axis=alt.Axis(title='Y')),
)
ps_v

<altair.VegaLite object>

In [15]:
rs = alt.Chart(data).mark_circle().encode(
    x=alt.X('ps_u', axis=alt.Axis(title='X')),
    y=alt.Y('ps_v', axis=alt.Axis(title='Y')),
)
rs

<altair.VegaLite object>

In [16]:
ls = alt.Chart(data).mark_circle().encode(
    x=alt.X('ps_l', axis=alt.Axis(title='l')),
    y=alt.Y('ps_delta', axis=alt.Axis(title='delta')),
)
ls

<altair.VegaLite object>

In [17]:
pm.r0

array([ -8.52985687e+01,   9.52011011e-05,   5.01515274e+02])

In [18]:
x = data.ps_u.values
x

array([  0.        ,   5.95988647,   4.43882625,   0.17366657,
        -4.5893787 ,  -6.53859689,  -4.58939842,   0.17364905,
         4.43883052,   9.96794807,   8.40310591,   0.85386401,
        -9.27416779, -12.35468077,  -9.27421661,   0.85386156,   8.4031256 ])

In [19]:
xp = data.ps_up.values
xp

array([ -1.60676591e-14,  -1.45962767e+01,  -9.51046470e+00,
         6.00889647e-01,   9.11213481e+00,   1.28485074e+01,
         9.11197889e+00,   6.00800626e-01,  -9.51045229e+00,
        -3.57767735e+01,  -2.03569265e+01,   2.98049414e+00,
         1.79417723e+01,   2.90572139e+01,   1.79413164e+01,
         2.98029970e+00,  -2.03567319e+01])

In [20]:
y = data.ps_v.values
y

array([  0.00000000e+00,   1.44751887e-06,   6.95578446e+00,
         9.53999461e+00,   6.63354154e+00,  -7.84061045e-06,
        -6.63354640e+00,  -9.53998533e+00,  -6.95577633e+00,
        -1.38818107e-06,   1.43805616e+01,   1.88485970e+01,
         1.31039921e+01,  -2.17856438e-05,  -1.31039989e+01,
        -1.88485581e+01,  -1.43805426e+01])

In [21]:
yp = data.ps_vp.values
yp

array([ -3.94632819e-20,   1.03777083e-05,  -9.48184004e-01,
        -2.44580332e+00,  -2.07038171e+00,  -7.21440274e-05,
         2.07034660e+00,   2.44591669e+00,   9.48268299e-01,
        -2.20674607e-05,  -1.47478248e-01,  -5.99824751e+00,
        -4.59189011e+00,  -1.96837636e-04,   4.59185257e+00,
         5.99870609e+00,   1.47716270e-01])

In [22]:
emittance(x,xp)

25.922206521320479

In [23]:
emittance(y,yp)

15.121320095481705

In [24]:
emittance_u(data)

25.922206521320479

In [25]:
emittance_v(data)

15.121320095481705